CREATE TABLE IF NOT EXISTS file_uploads (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    original_name VARCHAR(500) NOT NULL,
    row_count INT NOT NULL,
    uploaded_by VARCHAR(255),
    uploaded_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS excel_rows (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    file_upload_id BIGINT NOT NULL,
    cardindex_id VARCHAR(500),
    client_id VARCHAR(500),
    off_balance_account VARCHAR(500),
    card_index_type1 VARCHAR(500),
    client_name VARCHAR(1000),
    card_index_type2 VARCHAR(500),
    document_number VARCHAR(500),
    status VARCHAR(500),
    document_date VARCHAR(500),
    processing_date VARCHAR(500),
    document_amount VARCHAR(500),
    payment_balance VARCHAR(500),
    currency_code VARCHAR(50),
    currency VARCHAR(50),
    operation_type VARCHAR(500),
    payment_purpose VARCHAR(2000),
    payment_priority VARCHAR(500),
    payer_kpp VARCHAR(500),
    payer_inn VARCHAR(500),
    payer_name VARCHAR(1000),
    payer_corr_account VARCHAR(500),
    payer_bank_bik VARCHAR(500),
    payer_bank VARCHAR(1000),
    payer_account VARCHAR(500),
    kpp VARCHAR(500),
    recipient_inn VARCHAR(500),
    recipient_bank VARCHAR(1000),
    recipient_corr_account VARCHAR(500),
    recipient_bik VARCHAR(500),
    recipient_bank_name VARCHAR(1000),
    recipient_account VARCHAR(500),
    delivery_type VARCHAR(500),
    account_number_dt VARCHAR(500),
    account_number_kt VARCHAR(500),
    doc_card_index_eks_id VARCHAR(500),
    source_factory VARCHAR(500),
    text_return VARCHAR(2000),
    load_date VARCHAR(500),
    FOREIGN KEY (file_upload_id) REFERENCES file_uploads(id) ON DELETE CASCADE
);
